Canvas:
  CANVAS_SCALE:
    default: 1.0
    description: Scales exported figures and screenshots by this value
    max: 100.0
    min: 0.1
    value: 1.0
  CANVAS_SIZE:
    default:
    - 1024
    - 1024
    description: Height x width of the canvas when exporting a screenshot
    value:
    - 1024
    - 1024
  OVERRIDE_CANVAS_SIZE:
    default: false
    description: Whether to override the canvas size when exporting canvas screenshot
    value: false

Reader:
  CLEAR_LAYERS_ON_NEW_SCENE:
    default: false
    description: Whether to clear the viewer when selecting a new scene
    value: false
  PREFERRED_READER:
    default: bioio-ome-tiff
    description: Preferred reader to use when opening images
    value: bioio-ome-tiff
  SCENE_HANDLING:
    choices:
    - Open Scene Widget
    - View All Scenes
    - View First Scene Only
    default: Open Scene Widget
    description: How to handle files with multiple scenes
    value: Open Scene Widget
  UNPACK_CHANNELS_AS_LAYERS:
    default: true
    description: Whether to unpack channels as layers
    value: true
